INSERT INTO DBA_USERS (username, account_status, profile) VALUES ('ITAG_USER', 'OPEN', 'TAG_GENERAL');
INSERT INTO DBA_USERS (username, account_status, profile) VALUES ('ITAG_USER_ADM', 'OPEN', 'TAG_ADMIN');

INSERT INTO STAFF_MEMBERS (STAFF_ID, ASSIGNED_CASELOAD_ID, WORKING_CASELOAD_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAME, STATUS, SEX_CODE, BIRTHDATE) VALUES (STAFF_ID.nextval, 'MDI', 'MDI','USER', 'API', 'ITAG', 'ACTIVE', 'M', '1970-02-01');

INSERT INTO STAFF_USER_ACCOUNTS (USERNAME, STAFF_ID, STAFF_USER_TYPE, ID_SOURCE, WORKING_CASELOAD_ID) VALUES ('ITAG_USER', (SELECT STAFF_ID from STAFF_MEMBERS WHERE LAST_NAME = 'USER'), 'GENERAL', 'USER', 'MDI');
INSERT INTO STAFF_USER_ACCOUNTS (USERNAME, STAFF_ID, STAFF_USER_TYPE, ID_SOURCE, WORKING_CASELOAD_ID) VALUES ('ITAG_USER_ADM', (SELECT STAFF_ID from STAFF_MEMBERS WHERE LAST_NAME = 'USER'), 'ADMIN', 'USER', 'MDI');

INSERT INTO USER_ACCESSIBLE_CASELOADS (CASELOAD_ID, USERNAME, START_DATE) VALUES ('NWEB', 'ITAG_USER', sysdate);
INSERT INTO USER_ACCESSIBLE_CASELOADS (CASELOAD_ID, USERNAME, START_DATE) VALUES ('MDI', 'ITAG_USER', sysdate);
INSERT INTO USER_ACCESSIBLE_CASELOADS (CASELOAD_ID, USERNAME, START_DATE) VALUES ('NWEB', 'ITAG_USER_ADM', sysdate);
INSERT INTO USER_ACCESSIBLE_CASELOADS (CASELOAD_ID, USERNAME, START_DATE) VALUES ('CADM_I', 'ITAG_USER_ADM', sysdate);