---
# Per environment values which override defaults in nomis-user-roles-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: nomis-user-roles-api-dev.aks-dev-1.studio-hosting.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json

