---
# Per environment values which override defaults in nomis-user-roles-api/values.yaml

generic-service:
  replicaCount: 2

  poddisruptionbudget:
    enabled: true
    minAvailable: 1

  ingress:
    host: nomis-user-stage.aks-dev-1.studio-hosting.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-stage.hmpps.service.justice.gov.uk/auth
