---
# Per environment values which override defaults in nomis-user-roles-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: nomis-user-roles-api-preprod.prison.service.justice.gov.uk
    tlsSecretName: hmpps-nomis-user-roles-api-cert

  allowlist:
    groups:
      - internal

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    API_BASE_URL_OAUTH: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    FEATURE_RECORD-LOGON-DATE: true

  generic-prometheus-alerts:
    alertSeverity: hmpps_tech_non_prod
