---
# Per environment values which override defaults in nomis-user-roles-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: nomis-user-pp.aks-live-1.studio-hosting.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth

