CREATE TABLE LAA_CASELOADS
(
    CASELOAD_ID                   VARCHAR2(6)                       NOT NULL,
    LOCAL_AUTHORITY_CODE          VARCHAR2(6)                       NOT NULL,
    ACTIVE_FLAG                   VARCHAR2(1)  DEFAULT 'Y'          NOT NULL,
    EXPIRY_DATE                   DATE,
    CREATE_DATETIME               TIMESTAMP(9) DEFAULT systimestamp NOT NULL,
    CREATE_USER_ID                VARCHAR2(32) DEFAULT user()       NOT NULL,
    MODIFY_DATETIME               TIMESTAMP(9),
    MODIFY_USER_ID                VARCHAR2(32),
    AUDIT_TIMESTAMP               TIMESTAMP(9),
    AUDIT_USER_ID                 VARCHAR2(32),
    AUDIT_MODULE_NAME             VARCHAR2(65),
    AUDIT_CLIENT_USER_ID          VARCHAR2(64),
    AUDIT_CLIENT_IP_ADDRESS       VARCHAR2(39),
    AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64),
    AUDIT_ADDITIONAL_INFO         VARCHAR2(256),
    CONSTRAINT LAA_CASELOADS_PK PRIMARY KEY (CASELOAD_ID, LOCAL_AUTHORITY_CODE),
    CONSTRAINT LAA_CASELOADS_FK1 FOREIGN KEY (LOCAL_AUTHORITY_CODE)
        REFERENCES LOCAL_ADMIN_AUTHORITIES (LOCAL_AUTHORITY_CODE),
    CONSTRAINT LAA_CASELOADS_FK2 FOREIGN KEY (CASELOAD_ID)
        REFERENCES CASELOADS (CASELOAD_ID)

)